[package]
name = "rusty-flame"
version = "0.1.0"
authors = ["Craig Macomber <CraigM@CraigM.info>"]

[dependencies]
piston = "0.37.0"
piston2d-opengl_graphics = "0.53.0"
piston2d-graphics = "0.26.0"
pistoncore-glutin_window = "0.47.0"
nalgebra = "0.16.1"
alga = "0.7.1"
