[package]
name = "rusty-flame"
version = "0.1.0"
authors = ["Craig Macomber <CraigM@CraigM.info>"]
edition = "2018"

[dependencies]
piston = "0.49.0"
piston2d-opengl_graphics = "0.69.0"
piston2d-graphics = "0.35.0"
pistoncore-glutin_window = "0.63.0"
nalgebra = "0.18.1"
alga = "0.9.1"
piston_window = "0.105.0"
image = "0.22.2"
rand = "0.7.1"
failure = "0.1.5"
lazy_static = "1.4.0"
gfx-hal = "0.3.1"
reduce = "0.1.2"
vecmath = "1.0.0"

[dependencies.rendy]
version = "0.4.0"
features = ["texture-image", "shader-compiler", "vulkan"]

[dependencies.gfx-backend-vulkan]
version = "0.3.3"
features = ["x11"]
