[package]
name = "rusty-flame"
version = "0.1.0"
authors = ["Craig Macomber <CraigM@CraigM.info>"]
edition = "2018"

[dependencies]
piston = "0.49.0"
piston2d-opengl_graphics = "0.70.0"
piston2d-graphics = "0.35.0"
pistoncore-glutin_window = "0.63.0"
nalgebra = "0.19.0"
alga = "0.9.2"
piston_window = "0.105.0"
image = "0.22.3"
rand = "0.7.2"
failure = "0.1.6"
lazy_static = "1.4.0"
gfx-hal = "0.4.1"
reduce = "0.1.2"
vecmath = "1.0.0"
env_logger = "0.6"
log = "0.4"

genmesh = "0.6"
palette = "0.4"
rendy-core = "0.5.1"
rendy-shader = "0.5.1"

[dependencies.rendy]
version = "0.5.1"
features = ["texture-image", "shader-compiler", "vulkan", "init-winit"]

[dependencies.gfx-backend-vulkan]
version = "0.4.0"
features = ["x11"]
