[package]
name = "rusty-flame"
version = "0.1.0"
authors = ["Craig Macomber <CraigM@CraigM.info>"]
edition = "2018"

[dependencies]
piston = "0.49.0"
piston2d-opengl_graphics = "0.72.0"
piston2d-graphics = "0.36.0"
pistoncore-glutin_window = "0.63.0"
nalgebra = "0.20.0"
alga = "0.9.3"
piston_window = "0.107.0"
image = "0.23.2"
rand = "0.7.3"
failure = "0.1.7"
lazy_static = "1.4.0"
gfx-hal = "0.4.1"
reduce = "0.1.2"
vecmath = "1.0.0"
env_logger = "0.7.1"
log = { version = "0.4.8", features = ["max_level_debug", "release_max_level_info"] }
simple_logger = "1.6.0"
genmesh = "0.6.2"
palette = "0.5.0"
rendy-core = "0.5.1"
rendy-shader = "0.5.1"

[dependencies.rendy]
version = "0.5.1"
features = ["texture-image", "shader-compiler", "vulkan", "init-winit"]

[dependencies.gfx-backend-vulkan]
version = "0.4.1"
features = ["x11"]

