[package]
name = "rusty-flame"
version = "0.1.0"
authors = ["Craig Macomber <CraigM@CraigM.info>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/main.rs"

# [[bin]]
# name = "rusty-flame-native"

[dependencies]
nalgebra = "0.34.1"
log = { version = "0.4.17", features = [
    "max_level_warn",
    "release_max_level_info",
] }
winit = "0.30.13"
pollster = "0.4.0"
bytemuck = { version = "1.10.0", features = ["derive"] }
image = { version = "0.25.10", default-features = false, features = ["png"] }
salsa = "0.26.0"
salsa-macros =  "0.26.0"
num = { version = "0.4.3", default-features = false, features = [] }
egui = { version = "0.33.3", features = ["bytemuck"] }
wasm-timer = "0.2.5"
ordered-float = "5.1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# wgpu-subscriber = "0.1.0"
egui_wgpu_backend = "0.36.0"
egui_winit_platform = "0.28.0"
wgpu = "28.0.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
console_log = "1.0"
egui_wgpu_backend = { version = "0.36.0", features = ["web"] }
egui_winit_platform = { version = "0.28.0", features = ["webbrowser"] }
wasm-bindgen = "0.2.114"
wasm-bindgen-futures = "0.4.64"
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "Element",
    "Location",
] }
wgpu = { version = "28.0.0", features = ["webgl"] }
instant = { version = "0.1.13", features = ["wasm-bindgen"]}

[profile.dev]
opt-level = 1

[package.metadata.wasm-pack]
# wasm-opt = false
