[package]
name = "rusty-flame"
version = "0.1.0"
authors = ["Craig Macomber <CraigM@CraigM.info>"]
edition = "2018"

[dependencies]
piston = "0.52.1"
piston2d-opengl_graphics = "0.77.0"
piston2d-graphics = "0.39.0"
pistoncore-glutin_window = "0.68.0"
nalgebra = "0.24.1"
alga = "0.9.3"
piston_window = "0.117.0"
image = "0.23.13"
rand = "0.8.3"
failure = "0.1.8"
lazy_static = "1.4.0"
gfx-hal = "0.4.1"
reduce = "0.1.4"
vecmath = "1.0.0"
env_logger = "0.8.3"
log = { version = "0.4.14", features = ["max_level_warn", "release_max_level_info"] }
simple_logger = "1.11.0"
genmesh = "0.6.2"
palette = "0.5.0"
rendy-core = "0.5.1"
rendy-shader = "0.5.1"
wgpu = "0.7.0"
winit = { version = "0.24.0", features = ["web-sys"] }
futures = "0.3.12"
gfx-backend-vulkan = "0.7.0"
wgpu-subscriber = "0.1.0"
pollster = "0.2.1"
bytemuck = { version = "1.5.0", features = ["derive"] }

[dependencies.rendy]
version = "0.5.1"
features = ["texture-image", "shader-compiler", "vulkan", "init-winit" ] # "no-slow-safety-checks"
