[package]
name = "rusty-flame"
version = "0.1.0"
authors = ["Craig Macomber <CraigM@CraigM.info>"]
edition = "2018"

[dependencies]
nalgebra = "0.24.1"
reduce = "0.1.4"
log = { version = "0.4.14", features = ["max_level_warn", "release_max_level_info"] }
wgpu = "0.7.0"
winit = { version = "0.24.0", features = ["web-sys"] }
wgpu-subscriber = "0.1.0"
pollster = "0.2.1"
bytemuck = { version = "1.5.0", features = ["derive"] }

[patch.crates-io]
naga = { git = "https://github.com/gfx-rs/naga" }
