[package]
name = "rusty-flame"
version = "0.1.0"
authors = ["Craig Macomber <CraigM@CraigM.info>"]
edition = "2018"

[dependencies]
piston = "0.49.0"
piston2d-opengl_graphics = "0.66.0"
piston2d-graphics = "0.33.0"
pistoncore-glutin_window = "0.63.0"
nalgebra = "0.18.0"
alga = "0.9.1"
piston_window = "0.101.0"
image = "0.21.2"
rand = "0.7.0"

genmesh = "0.6.2"
env_logger = "0.6.1"
failure = "0.1.5"
lazy_static = "1.3.0"
log = "0.4.6"
winit = "0.19.1"
palette = "0.4.1"
gfx-hal = "0.2.1"

[dependencies.rendy]
version = "0.3.1"
features = ["texture-image", "shader-compiler", "vulkan"]